// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@2.1.0";

// src/lib/mcp/tools/read-agenda.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@2.1.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/read-agenda.ts
var read_agenda_default = defineTool({
  name: "read_agenda",
  title: "Leggi agenda",
  description: "Elenca gli appuntamenti dell'utente in un intervallo di date (formato AAAA-MM-GG).",
  inputSchema: {
    from: z.string().describe("Data iniziale inclusa, formato AAAA-MM-GG.").optional(),
    to: z.string().describe("Data finale inclusa, formato AAAA-MM-GG.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ from, to }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("appointments").select("id,date,time,name,type,status,planning_status,address,paese,microarea,current_visit_notes").is("deleted_at", null).order("date").order("time").limit(300);
    if (from) query = query.gte("date", from);
    if (to) query = query.lte("date", to);
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-doctors.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@2.1.0";
import { z as z2 } from "npm:zod@^3.25.76";
var search_doctors_default = defineTool2({
  name: "search_doctors",
  title: "Cerca medici",
  description: "Cerca i medici dello schedario per nome, specialit\xE0 o microarea.",
  inputSchema: {
    search: z2.string().describe("Testo da cercare nel nome del medico.").optional(),
    microarea: z2.string().describe("Codice microarea, ad esempio LE07.").optional(),
    limit: z2.number().int().describe("Numero massimo di risultati, massimo 100.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, microarea, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("doctors").select("id,name,specialty,paese,microarea,address,phone,office_hours,last_visit_date,birth_year").order("name").limit(Math.min(Math.max(limit ?? 50, 1), 100));
    if (microarea) query = query.eq("microarea", microarea.trim().toUpperCase());
    if (search) {
      const escaped = search.replaceAll("%", "\\%").replaceAll("_", "\\_");
      query = query.ilike("name", `%${escaped}%`);
    }
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { doctors: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-pharmacies.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@2.1.0";
import { z as z3 } from "npm:zod@^3.25.76";
var search_pharmacies_default = defineTool3({
  name: "search_pharmacies",
  title: "Cerca farmacie",
  description: "Cerca le farmacie salvate per nome o microarea.",
  inputSchema: {
    search: z3.string().describe("Testo da cercare nel nome della farmacia.").optional(),
    microarea: z3.string().describe("Codice microarea, ad esempio LE07.").optional(),
    limit: z3.number().int().describe("Numero massimo di risultati, massimo 100.").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, microarea, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("pharmacies").select("id,name,paese,microarea,address,phone,notes").order("name").limit(Math.min(Math.max(limit ?? 50, 1), 100));
    if (microarea) query = query.eq("microarea", microarea.trim().toUpperCase());
    if (search) {
      const escaped = search.replaceAll("%", "\\%").replaceAll("_", "\\_");
      query = query.ilike("name", `%${escaped}%`);
    }
    const { data, error } = await query;
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { pharmacies: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/read-daily-priorities.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@2.1.0";
import { z as z4 } from "npm:zod@^3.25.76";
var read_daily_priorities_default = defineTool4({
  name: "read_daily_priorities",
  title: "Leggi priorit\xE0 della giornata",
  description: "Legge le priorit\xE0 annotate per una data specifica (formato AAAA-MM-GG).",
  inputSchema: { date: z4.string().describe("Data della giornata, formato AAAA-MM-GG.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ date }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("daily_priorities").select("date,content").eq("date", date).maybeSingle();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [{ type: "text", text: data?.content ?? "Nessuna priorit\xE0 per questa data." }],
      structuredContent: { date, content: data?.content ?? null }
    };
  }
});

// src/lib/mcp/tools/create-appointment.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@2.1.0";
import { z as z5 } from "npm:zod@^3.25.76";
var create_appointment_default = defineTool5({
  name: "create_appointment",
  title: "Crea appuntamento",
  description: "Crea un nuovo appuntamento in agenda per l'utente collegato, con stato di pianificazione 'proposto'.",
  inputSchema: {
    date: z5.string().describe("Data dell'appuntamento, formato AAAA-MM-GG."),
    time: z5.string().describe("Orario dell'appuntamento, formato HH:MM."),
    name: z5.string().trim().describe("Nome del medico o della farmacia."),
    type: z5.enum(["medico", "farmacia"]).describe("Tipo di visita."),
    address: z5.string().describe("Indirizzo o struttura.").optional(),
    paese: z5.string().describe("Paese o comune.").optional(),
    microarea: z5.string().describe("Codice microarea, ad esempio LE07.").optional(),
    notes: z5.string().describe("Note sulla visita.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Non autenticato" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("appointments").insert({
      user_id: ctx.getUserId(),
      date: input.date,
      time: input.time,
      name: input.name,
      type: input.type,
      address: input.address ?? null,
      paese: input.paese ?? null,
      microarea: input.microarea ? input.microarea.trim().toUpperCase() : null,
      current_visit_notes: input.notes ?? null,
      status: "programmato",
      planning_status: "proposto",
      source: "ai"
    }).select().maybeSingle();
    return error ? { content: [{ type: "text", text: error.message }], isError: true } : {
      content: [
        { type: "text", text: `Appuntamento creato il ${input.date} alle ${input.time} con ${input.name}.` }
      ],
      structuredContent: { appointment: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dxyogaxdzrdxvprnojny";
var mcp_default = defineMcp({
  name: "medplanner-pro",
  title: "MedPlanner Pro",
  version: "0.1.0",
  instructions: "Strumenti di MedPlanner Pro per l'informatore scientifico collegato: leggere l'agenda, cercare medici e farmacie, leggere le priorit\xE0 della giornata e creare nuovi appuntamenti. Tutti i dati sono limitati all'utente autenticato.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [read_agenda_default, search_doctors_default, search_pharmacies_default, read_daily_priorities_default, create_appointment_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@2.1.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
